/* Generated by isagen from meow.isa in the MEOW repository.  Do not edit:
 * regenerate with "isagen -h meow_isa.h isa/meow.isa" and copy here. */
#ifndef MEOW_ISA_H
#define MEOW_ISA_H

#include <stdint.h>

enum meow_enc {
	MEOW_ENC_B,
	MEOW_ENC_ADD3,
	MEOW_ENC_ADD8,
	MEOW_ENC_SUB3,
	MEOW_ENC_SUB8,
	MEOW_ENC_CMPI,
	MEOW_ENC_CMPR,
	MEOW_ENC_TST,
	MEOW_ENC_MOV,
	MEOW_ENC_LDI,
	MEOW_ENC_SHI,
	MEOW_ENC_SHR,
	MEOW_ENC_BITR,
	MEOW_ENC_BITI,
	MEOW_ENC_MEM,
	MEOW_ENC_COUNT,
	MEOW_ENC_NONE = MEOW_ENC_COUNT
};

enum meow_field_kind {
	MEOW_FK_REG,
	MEOW_FK_BANK,
	MEOW_FK_UIMM,
	MEOW_FK_SIMM,
	MEOW_FK_COND,
	MEOW_FK_FLAG,
	MEOW_FK_OP
};

struct meow_field {
	const char *name;
	unsigned shift;
	unsigned width;
	enum meow_field_kind kind;
};

struct meow_enc_desc {
	const char *name;
	const char *bits;
	uint16_t mask;
	uint16_t match;
	unsigned nfields;
	const struct meow_field *fields;
};

extern const struct meow_enc_desc meow_encs[MEOW_ENC_COUNT];

enum meow_enc meow_enc_of(uint16_t word);

/* Sign-extend the low w bits of v. */
static inline int32_t meow_sext(uint32_t v, unsigned w)
{
	uint32_t m = 1u << (w - 1);

	return (int32_t)((v & (m + m - 1)) ^ m) - (int32_t)m;
}

/* B: 000ccccaaaaaaaaa */
#define MEOW_B_MASK 0xe000
#define MEOW_B_MATCH 0x0000
#define MEOW_B_COND_SHIFT 9
#define MEOW_B_COND_WIDTH 4
#define MEOW_B_COND(w) (((w) >> 9) & 0xf)
#define MEOW_B_OFF_SHIFT 0
#define MEOW_B_OFF_WIDTH 9
#define MEOW_B_OFF(w) (((w) >> 0) & 0x1ff)
#define MEOW_B_OFF_S(w) meow_sext(MEOW_B_OFF(w), 9)
#define MEOW_ENCODE_B(cond, off) \
	((uint16_t)(0x0000u \
	| (((uint32_t)(cond) & 0xfu) << 9) \
	| (((uint32_t)(off) & 0x1ffu) << 0)))

/* ADD3: 0010ddddiiiissss */
#define MEOW_ADD3_MASK 0xf000
#define MEOW_ADD3_MATCH 0x2000
#define MEOW_ADD3_RD_SHIFT 8
#define MEOW_ADD3_RD_WIDTH 4
#define MEOW_ADD3_RD(w) (((w) >> 8) & 0xf)
#define MEOW_ADD3_IMM_SHIFT 4
#define MEOW_ADD3_IMM_WIDTH 4
#define MEOW_ADD3_IMM(w) (((w) >> 4) & 0xf)
#define MEOW_ADD3_RS_SHIFT 0
#define MEOW_ADD3_RS_WIDTH 4
#define MEOW_ADD3_RS(w) (((w) >> 0) & 0xf)
#define MEOW_ENCODE_ADD3(rd, imm, rs) \
	((uint16_t)(0x2000u \
	| (((uint32_t)(rd) & 0xfu) << 8) \
	| (((uint32_t)(imm) & 0xfu) << 4) \
	| (((uint32_t)(rs) & 0xfu) << 0)))

/* ADD8: 0011ddddiiiiiiii */
#define MEOW_ADD8_MASK 0xf000
#define MEOW_ADD8_MATCH 0x3000
#define MEOW_ADD8_RD_SHIFT 8
#define MEOW_ADD8_RD_WIDTH 4
#define MEOW_ADD8_RD(w) (((w) >> 8) & 0xf)
#define MEOW_ADD8_IMM_SHIFT 0
#define MEOW_ADD8_IMM_WIDTH 8
#define MEOW_ADD8_IMM(w) (((w) >> 0) & 0xff)
#define MEOW_ENCODE_ADD8(rd, imm) \
	((uint16_t)(0x3000u \
	| (((uint32_t)(rd) & 0xfu) << 8) \
	| (((uint32_t)(imm) & 0xffu) << 0)))

/* SUB3: 0100ddddiiiissss */
#define MEOW_SUB3_MASK 0xf000
#define MEOW_SUB3_MATCH 0x4000
#define MEOW_SUB3_RD_SHIFT 8
#define MEOW_SUB3_RD_WIDTH 4
#define MEOW_SUB3_RD(w) (((w) >> 8) & 0xf)
#define MEOW_SUB3_IMM_SHIFT 4
#define MEOW_SUB3_IMM_WIDTH 4
#define MEOW_SUB3_IMM(w) (((w) >> 4) & 0xf)
#define MEOW_SUB3_RS_SHIFT 0
#define MEOW_SUB3_RS_WIDTH 4
#define MEOW_SUB3_RS(w) (((w) >> 0) & 0xf)
#define MEOW_ENCODE_SUB3(rd, imm, rs) \
	((uint16_t)(0x4000u \
	| (((uint32_t)(rd) & 0xfu) << 8) \
	| (((uint32_t)(imm) & 0xfu) << 4) \
	| (((uint32_t)(rs) & 0xfu) << 0)))

/* SUB8: 0101ddddiiiiiiii */
#define MEOW_SUB8_MASK 0xf000
#define MEOW_SUB8_MATCH 0x5000
#define MEOW_SUB8_RD_SHIFT 8
#define MEOW_SUB8_RD_WIDTH 4
#define MEOW_SUB8_RD(w) (((w) >> 8) & 0xf)
#define MEOW_SUB8_IMM_SHIFT 0
#define MEOW_SUB8_IMM_WIDTH 8
#define MEOW_SUB8_IMM(w) (((w) >> 0) & 0xff)
#define MEOW_ENCODE_SUB8(rd, imm) \
	((uint16_t)(0x5000u \
	| (((uint32_t)(rd) & 0xfu) << 8) \
	| (((uint32_t)(imm) & 0xffu) << 0)))

/* CMPI: 0110nnnniiiiiiii */
#define MEOW_CMPI_MASK 0xf000
#define MEOW_CMPI_MATCH 0x6000
#define MEOW_CMPI_RN_SHIFT 8
#define MEOW_CMPI_RN_WIDTH 4
#define MEOW_CMPI_RN(w) (((w) >> 8) & 0xf)
#define MEOW_CMPI_IMM_SHIFT 0
#define MEOW_CMPI_IMM_WIDTH 8
#define MEOW_CMPI_IMM(w) (((w) >> 0) & 0xff)
#define MEOW_CMPI_IMM_S(w) meow_sext(MEOW_CMPI_IMM(w), 8)
#define MEOW_ENCODE_CMPI(rn, imm) \
	((uint16_t)(0x6000u \
	| (((uint32_t)(rn) & 0xfu) << 8) \
	| (((uint32_t)(imm) & 0xffu) << 0)))

/* CMPR: 0111nnnn00wxmmmm */
#define MEOW_CMPR_MASK 0xf0c0
#define MEOW_CMPR_MATCH 0x7000
#define MEOW_CMPR_RN_SHIFT 8
#define MEOW_CMPR_RN_WIDTH 4
#define MEOW_CMPR_RN(w) (((w) >> 8) & 0xf)
#define MEOW_CMPR_BN_SHIFT 5
#define MEOW_CMPR_BN_WIDTH 1
#define MEOW_CMPR_BN(w) (((w) >> 5) & 0x1)
#define MEOW_CMPR_BM_SHIFT 4
#define MEOW_CMPR_BM_WIDTH 1
#define MEOW_CMPR_BM(w) (((w) >> 4) & 0x1)
#define MEOW_CMPR_RM_SHIFT 0
#define MEOW_CMPR_RM_WIDTH 4
#define MEOW_CMPR_RM(w) (((w) >> 0) & 0xf)
#define MEOW_ENCODE_CMPR(rn, bn, bm, rm) \
	((uint16_t)(0x7000u \
	| (((uint32_t)(rn) & 0xfu) << 8) \
	| (((uint32_t)(bn) & 0x1u) << 5) \
	| (((uint32_t)(bm) & 0x1u) << 4) \
	| (((uint32_t)(rm) & 0xfu) << 0)))

/* TST: 0111nnnn10wbbbbb */
#define MEOW_TST_MASK 0xf0c0
#define MEOW_TST_MATCH 0x7080
#define MEOW_TST_RN_SHIFT 8
#define MEOW_TST_RN_WIDTH 4
#define MEOW_TST_RN(w) (((w) >> 8) & 0xf)
#define MEOW_TST_BN_SHIFT 5
#define MEOW_TST_BN_WIDTH 1
#define MEOW_TST_BN(w) (((w) >> 5) & 0x1)
#define MEOW_TST_BIT_SHIFT 0
#define MEOW_TST_BIT_WIDTH 5
#define MEOW_TST_BIT(w) (((w) >> 0) & 0x1f)
#define MEOW_ENCODE_TST(rn, bn, bit) \
	((uint16_t)(0x7080u \
	| (((uint32_t)(rn) & 0xfu) << 8) \
	| (((uint32_t)(bn) & 0x1u) << 5) \
	| (((uint32_t)(bit) & 0x1fu) << 0)))

/* MOV: 1000ddddbhwxssss */
#define MEOW_MOV_MASK 0xf000
#define MEOW_MOV_MATCH 0x8000
#define MEOW_MOV_RD_SHIFT 8
#define MEOW_MOV_RD_WIDTH 4
#define MEOW_MOV_RD(w) (((w) >> 8) & 0xf)
#define MEOW_MOV_BSW_SHIFT 7
#define MEOW_MOV_BSW_WIDTH 1
#define MEOW_MOV_BSW(w) (((w) >> 7) & 0x1)
#define MEOW_MOV_HSW_SHIFT 6
#define MEOW_MOV_HSW_WIDTH 1
#define MEOW_MOV_HSW(w) (((w) >> 6) & 0x1)
#define MEOW_MOV_BD_SHIFT 5
#define MEOW_MOV_BD_WIDTH 1
#define MEOW_MOV_BD(w) (((w) >> 5) & 0x1)
#define MEOW_MOV_BS_SHIFT 4
#define MEOW_MOV_BS_WIDTH 1
#define MEOW_MOV_BS(w) (((w) >> 4) & 0x1)
#define MEOW_MOV_RS_SHIFT 0
#define MEOW_MOV_RS_WIDTH 4
#define MEOW_MOV_RS(w) (((w) >> 0) & 0xf)
#define MEOW_ENCODE_MOV(rd, bsw, hsw, bd, bs, rs) \
	((uint16_t)(0x8000u \
	| (((uint32_t)(rd) & 0xfu) << 8) \
	| (((uint32_t)(bsw) & 0x1u) << 7) \
	| (((uint32_t)(hsw) & 0x1u) << 6) \
	| (((uint32_t)(bd) & 0x1u) << 5) \
	| (((uint32_t)(bs) & 0x1u) << 4) \
	| (((uint32_t)(rs) & 0xfu) << 0)))

/* LDI: 1001iiiiiiiiiiii */
#define MEOW_LDI_MASK 0xf000
#define MEOW_LDI_MATCH 0x9000
#define MEOW_LDI_IMM_SHIFT 0
#define MEOW_LDI_IMM_WIDTH 12
#define MEOW_LDI_IMM(w) (((w) >> 0) & 0xfff)
#define MEOW_LDI_IMM_S(w) meow_sext(MEOW_LDI_IMM(w), 12)
#define MEOW_ENCODE_LDI(imm) \
	((uint16_t)(0x9000u \
	| (((uint32_t)(imm) & 0xfffu) << 0)))

/* SHI: 101arrrrdR0iiiii */
#define MEOW_SHI_MASK 0xe020
#define MEOW_SHI_MATCH 0xa000
#define MEOW_SHI_ARITH_SHIFT 12
#define MEOW_SHI_ARITH_WIDTH 1
#define MEOW_SHI_ARITH(w) (((w) >> 12) & 0x1)
#define MEOW_SHI_RD_SHIFT 8
#define MEOW_SHI_RD_WIDTH 4
#define MEOW_SHI_RD(w) (((w) >> 8) & 0xf)
#define MEOW_SHI_LEFT_SHIFT 7
#define MEOW_SHI_LEFT_WIDTH 1
#define MEOW_SHI_LEFT(w) (((w) >> 7) & 0x1)
#define MEOW_SHI_ROT_SHIFT 6
#define MEOW_SHI_ROT_WIDTH 1
#define MEOW_SHI_ROT(w) (((w) >> 6) & 0x1)
#define MEOW_SHI_IMM_SHIFT 0
#define MEOW_SHI_IMM_WIDTH 5
#define MEOW_SHI_IMM(w) (((w) >> 0) & 0x1f)
#define MEOW_ENCODE_SHI(arith, rd, left, rot, imm) \
	((uint16_t)(0xa000u \
	| (((uint32_t)(arith) & 0x1u) << 12) \
	| (((uint32_t)(rd) & 0xfu) << 8) \
	| (((uint32_t)(left) & 0x1u) << 7) \
	| (((uint32_t)(rot) & 0x1u) << 6) \
	| (((uint32_t)(imm) & 0x1fu) << 0)))

/* SHR: 101arrrrdR10ssss */
#define MEOW_SHR_MASK 0xe030
#define MEOW_SHR_MATCH 0xa020
#define MEOW_SHR_ARITH_SHIFT 12
#define MEOW_SHR_ARITH_WIDTH 1
#define MEOW_SHR_ARITH(w) (((w) >> 12) & 0x1)
#define MEOW_SHR_RD_SHIFT 8
#define MEOW_SHR_RD_WIDTH 4
#define MEOW_SHR_RD(w) (((w) >> 8) & 0xf)
#define MEOW_SHR_LEFT_SHIFT 7
#define MEOW_SHR_LEFT_WIDTH 1
#define MEOW_SHR_LEFT(w) (((w) >> 7) & 0x1)
#define MEOW_SHR_ROT_SHIFT 6
#define MEOW_SHR_ROT_WIDTH 1
#define MEOW_SHR_ROT(w) (((w) >> 6) & 0x1)
#define MEOW_SHR_RS_SHIFT 0
#define MEOW_SHR_RS_WIDTH 4
#define MEOW_SHR_RS(w) (((w) >> 0) & 0xf)
#define MEOW_ENCODE_SHR(arith, rd, left, rot, rs) \
	((uint16_t)(0xa020u \
	| (((uint32_t)(arith) & 0x1u) << 12) \
	| (((uint32_t)(rd) & 0xfu) << 8) \
	| (((uint32_t)(left) & 0x1u) << 7) \
	| (((uint32_t)(rot) & 0x1u) << 6) \
	| (((uint32_t)(rs) & 0xfu) << 0)))

/* BITR: 110nddddoo00ssss */
#define MEOW_BITR_MASK 0xe030
#define MEOW_BITR_MATCH 0xc000
#define MEOW_BITR_INV_SHIFT 12
#define MEOW_BITR_INV_WIDTH 1
#define MEOW_BITR_INV(w) (((w) >> 12) & 0x1)
#define MEOW_BITR_RD_SHIFT 8
#define MEOW_BITR_RD_WIDTH 4
#define MEOW_BITR_RD(w) (((w) >> 8) & 0xf)
#define MEOW_BITR_OP_SHIFT 6
#define MEOW_BITR_OP_WIDTH 2
#define MEOW_BITR_OP(w) (((w) >> 6) & 0x3)
#define MEOW_BITR_RS_SHIFT 0
#define MEOW_BITR_RS_WIDTH 4
#define MEOW_BITR_RS(w) (((w) >> 0) & 0xf)
#define MEOW_ENCODE_BITR(inv, rd, op, rs) \
	((uint16_t)(0xc000u \
	| (((uint32_t)(inv) & 0x1u) << 12) \
	| (((uint32_t)(rd) & 0xfu) << 8) \
	| (((uint32_t)(op) & 0x3u) << 6) \
	| (((uint32_t)(rs) & 0xfu) << 0)))

/* BITI: 110nddddoo1bbbbb */
#define MEOW_BITI_MASK 0xe020
#define MEOW_BITI_MATCH 0xc020
#define MEOW_BITI_INV_SHIFT 12
#define MEOW_BITI_INV_WIDTH 1
#define MEOW_BITI_INV(w) (((w) >> 12) & 0x1)
#define MEOW_BITI_RD_SHIFT 8
#define MEOW_BITI_RD_WIDTH 4
#define MEOW_BITI_RD(w) (((w) >> 8) & 0xf)
#define MEOW_BITI_OP_SHIFT 6
#define MEOW_BITI_OP_WIDTH 2
#define MEOW_BITI_OP(w) (((w) >> 6) & 0x3)
#define MEOW_BITI_BIT_SHIFT 0
#define MEOW_BITI_BIT_WIDTH 5
#define MEOW_BITI_BIT(w) (((w) >> 0) & 0x1f)
#define MEOW_ENCODE_BITI(inv, rd, op, bit) \
	((uint16_t)(0xc020u \
	| (((uint32_t)(inv) & 0x1u) << 12) \
	| (((uint32_t)(rd) & 0xfu) << 8) \
	| (((uint32_t)(op) & 0x3u) << 6) \
	| (((uint32_t)(bit) & 0x1fu) << 0)))

/* MEM: 111LvvvvSHWDaaaa */
#define MEOW_MEM_MASK 0xe000
#define MEOW_MEM_MATCH 0xe000
#define MEOW_MEM_STORE_SHIFT 12
#define MEOW_MEM_STORE_WIDTH 1
#define MEOW_MEM_STORE(w) (((w) >> 12) & 0x1)
#define MEOW_MEM_RV_SHIFT 8
#define MEOW_MEM_RV_WIDTH 4
#define MEOW_MEM_RV(w) (((w) >> 8) & 0xf)
#define MEOW_MEM_HALF_SHIFT 7
#define MEOW_MEM_HALF_WIDTH 1
#define MEOW_MEM_HALF(w) (((w) >> 7) & 0x1)
#define MEOW_MEM_HILO_SHIFT 6
#define MEOW_MEM_HILO_WIDTH 1
#define MEOW_MEM_HILO(w) (((w) >> 6) & 0x1)
#define MEOW_MEM_WB_SHIFT 5
#define MEOW_MEM_WB_WIDTH 1
#define MEOW_MEM_WB(w) (((w) >> 5) & 0x1)
#define MEOW_MEM_DIR_SHIFT 4
#define MEOW_MEM_DIR_WIDTH 1
#define MEOW_MEM_DIR(w) (((w) >> 4) & 0x1)
#define MEOW_MEM_RA_SHIFT 0
#define MEOW_MEM_RA_WIDTH 4
#define MEOW_MEM_RA(w) (((w) >> 0) & 0xf)
#define MEOW_ENCODE_MEM(store, rv, half, hilo, wb, dir, ra) \
	((uint16_t)(0xe000u \
	| (((uint32_t)(store) & 0x1u) << 12) \
	| (((uint32_t)(rv) & 0xfu) << 8) \
	| (((uint32_t)(half) & 0x1u) << 7) \
	| (((uint32_t)(hilo) & 0x1u) << 6) \
	| (((uint32_t)(wb) & 0x1u) << 5) \
	| (((uint32_t)(dir) & 0x1u) << 4) \
	| (((uint32_t)(ra) & 0xfu) << 0)))

#endif /* MEOW_ISA_H */
