/* Generated by isagen from meow.isa in the MEOW repository.  Do not edit:
 * regenerate with "isagen -c meow_isa.c isa/meow.isa" and copy here. */
#include "meow_isa.h"

static const struct meow_field fields_B[] = {
	{ "cond", 9, 4, MEOW_FK_COND },
	{ "off", 0, 9, MEOW_FK_SIMM },
};

static const struct meow_field fields_ADD3[] = {
	{ "rd", 8, 4, MEOW_FK_REG },
	{ "imm", 4, 4, MEOW_FK_UIMM },
	{ "rs", 0, 4, MEOW_FK_REG },
};

static const struct meow_field fields_ADD8[] = {
	{ "rd", 8, 4, MEOW_FK_REG },
	{ "imm", 0, 8, MEOW_FK_UIMM },
};

static const struct meow_field fields_SUB3[] = {
	{ "rd", 8, 4, MEOW_FK_REG },
	{ "imm", 4, 4, MEOW_FK_UIMM },
	{ "rs", 0, 4, MEOW_FK_REG },
};

static const struct meow_field fields_SUB8[] = {
	{ "rd", 8, 4, MEOW_FK_REG },
	{ "imm", 0, 8, MEOW_FK_UIMM },
};

static const struct meow_field fields_CMPI[] = {
	{ "rn", 8, 4, MEOW_FK_REG },
	{ "imm", 0, 8, MEOW_FK_SIMM },
};

static const struct meow_field fields_CMPR[] = {
	{ "rn", 8, 4, MEOW_FK_REG },
	{ "bn", 5, 1, MEOW_FK_BANK },
	{ "bm", 4, 1, MEOW_FK_BANK },
	{ "rm", 0, 4, MEOW_FK_REG },
};

static const struct meow_field fields_TST[] = {
	{ "rn", 8, 4, MEOW_FK_REG },
	{ "bn", 5, 1, MEOW_FK_BANK },
	{ "bit", 0, 5, MEOW_FK_UIMM },
};

static const struct meow_field fields_MOV[] = {
	{ "rd", 8, 4, MEOW_FK_REG },
	{ "bsw", 7, 1, MEOW_FK_FLAG },
	{ "hsw", 6, 1, MEOW_FK_FLAG },
	{ "bd", 5, 1, MEOW_FK_BANK },
	{ "bs", 4, 1, MEOW_FK_BANK },
	{ "rs", 0, 4, MEOW_FK_REG },
};

static const struct meow_field fields_LDI[] = {
	{ "imm", 0, 12, MEOW_FK_SIMM },
};

static const struct meow_field fields_SHI[] = {
	{ "rd", 8, 4, MEOW_FK_REG },
	{ "left", 7, 1, MEOW_FK_FLAG },
	{ "rot", 6, 1, MEOW_FK_FLAG },
	{ "imm", 0, 5, MEOW_FK_UIMM },
};

static const struct meow_field fields_SHR[] = {
	{ "rd", 8, 4, MEOW_FK_REG },
	{ "left", 7, 1, MEOW_FK_FLAG },
	{ "rot", 6, 1, MEOW_FK_FLAG },
	{ "rs", 0, 4, MEOW_FK_REG },
};

static const struct meow_field fields_ASRI[] = {
	{ "rd", 8, 4, MEOW_FK_REG },
	{ "imm", 0, 5, MEOW_FK_UIMM },
};

static const struct meow_field fields_ASRR[] = {
	{ "rd", 8, 4, MEOW_FK_REG },
	{ "rs", 0, 4, MEOW_FK_REG },
};

static const struct meow_field fields_ADDSI[] = {
	{ "rd", 8, 4, MEOW_FK_REG },
	{ "sub", 6, 1, MEOW_FK_FLAG },
	{ "imm", 0, 5, MEOW_FK_UIMM },
};

static const struct meow_field fields_ADDSR[] = {
	{ "rd", 8, 4, MEOW_FK_REG },
	{ "sub", 6, 1, MEOW_FK_FLAG },
	{ "rs", 0, 4, MEOW_FK_REG },
};

static const struct meow_field fields_SPMEM[] = {
	{ "rv", 8, 4, MEOW_FK_REG },
	{ "store", 5, 1, MEOW_FK_FLAG },
	{ "imm", 0, 5, MEOW_FK_UIMM },
};

static const struct meow_field fields_BITR[] = {
	{ "inv", 12, 1, MEOW_FK_FLAG },
	{ "rd", 8, 4, MEOW_FK_REG },
	{ "op", 6, 2, MEOW_FK_OP },
	{ "rs", 0, 4, MEOW_FK_REG },
};

static const struct meow_field fields_BITI[] = {
	{ "inv", 12, 1, MEOW_FK_FLAG },
	{ "rd", 8, 4, MEOW_FK_REG },
	{ "op", 6, 2, MEOW_FK_OP },
	{ "bit", 0, 5, MEOW_FK_UIMM },
};

static const struct meow_field fields_MEM[] = {
	{ "store", 12, 1, MEOW_FK_FLAG },
	{ "rv", 8, 4, MEOW_FK_REG },
	{ "half", 7, 1, MEOW_FK_FLAG },
	{ "hilo", 6, 1, MEOW_FK_FLAG },
	{ "wb", 5, 1, MEOW_FK_FLAG },
	{ "dir", 4, 1, MEOW_FK_FLAG },
	{ "ra", 0, 4, MEOW_FK_REG },
};

const struct meow_enc_desc meow_encs[MEOW_ENC_COUNT] = {
	{ "B", "000ccccaaaaaaaaa", 0xe000, 0x0000, 2, fields_B },
	{ "ADD3", "0010ddddiiiissss", 0xf000, 0x2000, 3, fields_ADD3 },
	{ "ADD8", "0011ddddiiiiiiii", 0xf000, 0x3000, 2, fields_ADD8 },
	{ "SUB3", "0100ddddiiiissss", 0xf000, 0x4000, 3, fields_SUB3 },
	{ "SUB8", "0101ddddiiiiiiii", 0xf000, 0x5000, 2, fields_SUB8 },
	{ "CMPI", "0110nnnniiiiiiii", 0xf000, 0x6000, 2, fields_CMPI },
	{ "CMPR", "0111nnnn00wxmmmm", 0xf0c0, 0x7000, 4, fields_CMPR },
	{ "TST", "0111nnnn10wbbbbb", 0xf0c0, 0x7080, 3, fields_TST },
	{ "MOV", "1000ddddbhwxssss", 0xf000, 0x8000, 6, fields_MOV },
	{ "LDI", "1001iiiiiiiiiiii", 0xf000, 0x9000, 1, fields_LDI },
	{ "SHI", "1010rrrrdR0iiiii", 0xf020, 0xa000, 4, fields_SHI },
	{ "SHR", "1010rrrrdR10ssss", 0xf030, 0xa020, 4, fields_SHR },
	{ "ASRI", "1011rrrr000iiiii", 0xf0e0, 0xb000, 2, fields_ASRI },
	{ "ASRR", "1011rrrr0010ssss", 0xf0f0, 0xb020, 2, fields_ASRR },
	{ "ADDSI", "1011dddd1s0iiiii", 0xf0a0, 0xb080, 3, fields_ADDSI },
	{ "ADDSR", "1011dddd1s10rrrr", 0xf0b0, 0xb0a0, 3, fields_ADDSR },
	{ "SPMEM", "1011vvvv01Looooo", 0xf0c0, 0xb040, 3, fields_SPMEM },
	{ "BITR", "110nddddoo00ssss", 0xe030, 0xc000, 4, fields_BITR },
	{ "BITI", "110nddddoo1bbbbb", 0xe020, 0xc020, 4, fields_BITI },
	{ "MEM", "111LvvvvSHWDaaaa", 0xe000, 0xe000, 7, fields_MEM },
};

enum meow_enc meow_enc_of(uint16_t word)
{
	unsigned i;

	for (i = 0; i < MEOW_ENC_COUNT; i++) {
		if ((word & meow_encs[i].mask) == meow_encs[i].match) {
			return (enum meow_enc)i;
		}
	}
	return MEOW_ENC_NONE;
}
